# Generated by Django 4.1.7 on 2023-02-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='earn',
            field=models.IntegerField(default=1, verbose_name='earn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='earn_rate',
            field=models.FloatField(default=1, verbose_name='earn_rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='info',
            field=models.CharField(default=1, max_length=256, verbose_name='info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='profit1',
            field=models.FloatField(default=1, verbose_name='profit1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='profit2',
            field=models.FloatField(default=11, verbose_name='profit2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='profit3',
            field=models.FloatField(default=1, verbose_name='profit3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='profit4',
            field=models.FloatField(default=1, verbose_name='profit4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklist',
            name='target_price',
            field=models.FloatField(default=1, verbose_name='target_price'),
            preserve_default=False,
        ),
    ]
