# Generated by Django 4.1.7 on 2023-02-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='high_rate',
            field=models.IntegerField(verbose_name='high_rate'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='trading_volume',
            field=models.IntegerField(verbose_name='trading_volume'),
        ),
    ]
