# Generated by Django 4.1.7 on 2023-02-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_portfolio_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=128, verbose_name='stock_name')),
                ('stock_share', models.IntegerField(verbose_name='stock_share')),
                ('invest_amount', models.IntegerField(verbose_name='invest_amount')),
                ('earn_rate', models.IntegerField(verbose_name='earn_rate')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='포트폴리오명')),
            ],
            options={
                'verbose_name': '보유주식',
                'verbose_name_plural': '보유주식',
                'db_table': 'holdingstock',
            },
        ),
    ]
