# Generated by Django 4.1.7 on 2023-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdingstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingstock',
            name='earn_rate',
            field=models.FloatField(verbose_name='earn_rate'),
        ),
        migrations.AlterField(
            model_name='holdingstock',
            name='stock_share',
            field=models.FloatField(verbose_name='stock_share'),
        ),
    ]
