# Generated by Django 4.1.7 on 2023-02-20 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdingstock', '0002_alter_holdingstock_earn_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingstock',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='보유자'),
            preserve_default=False,
        ),
    ]
