# Generated by Django 4.1.7 on 2023-02-20 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdingstock', '0003_holdingstock_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingstock',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
