# Generated by Django 4.1.7 on 2023-02-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdingstock', '0005_holdingstock_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingstock',
            name='stock_code',
            field=models.CharField(max_length=128, verbose_name='stock_code'),
        ),
    ]
