# Generated by Django 4.1.7 on 2023-02-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invest', models.IntegerField(verbose_name='total_invest')),
                ('total_rate', models.IntegerField(verbose_name='total_rate')),
                ('total_earn', models.IntegerField(verbose_name='total_earn')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'verbose_name_plural': '포트폴리오',
                'db_table': 'portfolio',
            },
        ),
    ]
