# Generated by Django 4.1.7 on 2023-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_rate',
            field=models.FloatField(verbose_name='total_rate'),
        ),
    ]
