# Generated by Django 4.1.7 on 2023-02-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocklist', '0002_alter_stocklist_high_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField(verbose_name='current_price')),
                ('earn', models.IntegerField(verbose_name='earn')),
                ('earn_rate', models.IntegerField(verbose_name='earn_rate')),
                ('info', models.CharField(max_length=256, verbose_name='info')),
                ('profit1', models.IntegerField(verbose_name='profit1')),
                ('profit2', models.IntegerField(verbose_name='profit2')),
                ('profit3', models.IntegerField(verbose_name='profit3')),
                ('profit4', models.IntegerField(verbose_name='profit4')),
                ('target_price', models.IntegerField(verbose_name='target_price')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocklist.stocklist', verbose_name='주식아이디')),
            ],
            options={
                'verbose_name': '주식상세리스트',
                'verbose_name_plural': '주식상세리스트',
                'db_table': 'stock_detail',
            },
        ),
    ]
