# Generated by Django 4.1.7 on 2023-02-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='profit4',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='target_price',
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='month3',
            field=models.CharField(default=1, max_length=256, verbose_name='month3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='sales1',
            field=models.IntegerField(default=1, verbose_name='sales1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='sales2',
            field=models.IntegerField(default=1, verbose_name='sales2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='sales3',
            field=models.IntegerField(default=1, verbose_name='sales3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='week',
            field=models.CharField(default=1, max_length=256, verbose_name='week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='year',
            field=models.CharField(default=1, max_length=256, verbose_name='year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='year3',
            field=models.CharField(default=1, max_length=256, verbose_name='year3'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='뉴스 제목')),
                ('tstamp', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdetail.stockdetail', verbose_name='상품')),
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스',
                'db_table': 'news',
            },
        ),
    ]
