# Generated by Django 4.1.7 on 2023-02-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0002_remove_stockdetail_profit4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='stock_code',
            field=models.IntegerField(default=1, verbose_name='stock_code'),
            preserve_default=False,
        ),
    ]
