# Generated by Django 4.1.7 on 2023-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0003_stockdetail_stock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='stock_name'),
            preserve_default=False,
        ),
    ]
