# Generated by Django 4.1.7 on 2023-02-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0004_stockdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='current_price'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='earn',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='earn'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='earn_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='earn_rate'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='profit1',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='profit1'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='profit2',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='profit2'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='profit3',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='profit3'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sales1',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='sales1'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sales2',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='sales2'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sales3',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='sales3'),
        ),
    ]
