# Generated by Django 4.1.7 on 2023-02-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0006_alter_stockdetail_profit1_alter_stockdetail_profit2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='News',
        ),
    ]
