# Generated by Django 4.1.7 on 2023-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0007_rename_comment_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='stock',
        ),
        migrations.AddField(
            model_name='news',
            name='stock_code',
            field=models.IntegerField(default=1, verbose_name='stock_code'),
            preserve_default=False,
        ),
    ]
