# Generated by Django 4.1.7 on 2023-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0008_remove_news_stock_news_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tstamp',
            field=models.CharField(max_length=10, verbose_name='날짜'),
        ),
    ]
