# Generated by Django 4.1.7 on 2023-02-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdetail', '0009_alter_news_tstamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='current_price',
            field=models.IntegerField(verbose_name='current_price'),
        ),
    ]
